name: CI Pipeline Check

on:
  push:
    branches: ['**']

jobs:
  ci_pipeline_check:
    name: CI Pipeline Check  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Build Documentation
        run: npm run docs

